<?php 
/*------------------------------------------------------------------------
# ArexMage
# ------------------------------------------------------------------------
# Copyright (C) 2013 ArexMage. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: ArexMage
# Websites: http://www.arexmage.com
-------------------------------------------------------------------------*/ 
$config = Mage::getStoreConfig('mtcolinusadmin/mtcolinusadmin_appearance'); 
if($config['theme_responsive']){	
?>
<?php 
	$title=Mage::getStoreConfig('mtcolinusadmin/smartmenu/title');
	$style=Mage::getStoreConfig('mtcolinusadmin/smartmenu/menustyle');
	$event=Mage::getStoreConfig('mtcolinusadmin/smartmenu/event');  
?>
<div class="mt-drillmenu hidden-desktop">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="mt-nav-container">
				<div class="block-title clearfix">
					<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<span class="brand"><?php echo $this->__('Navigation');?></span>
				</div>				
				<div class="nav-collapse collapse"> 
					<script type="text/javascript"> 
						$mtkb(document).ready(function() {
							$mtkb("#mt_accordionmenu").mtAccordionMenu({
								accordion:true,
								speed: 500,
								closedSign: 'collapse',
								openedSign: 'expand',
								mouseType: 0,
								easing: 'easeInOutBack'
							});
						}); 
					</script>
					<ul id="mt_accordionmenu" class="nav-accordion">
						<li><a href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->__('Home'); ?></a></li>
						<?php foreach ($this->getStoreCategories() as $_category): ?>
							<?php echo $this->drawItem($_category) ?>
						<?php endforeach ?>
					</ul> 
				</div>
			</div>
		</div>
	</div>
</div> 
<?php }?>
