<?php
/*------------------------------------------------------------------------
# ArexMage
# ------------------------------------------------------------------------
# Copyright (C) 2013 ArexMage. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: ArexMage
# Websites: http://www.arexmage.com
-------------------------------------------------------------------------*/
$config = Mage::getStoreConfig('mtcolinusadmin/mtcolinusadmin_appearance');
$otherconfig = Mage::getStoreConfig('mtcolinusadmin/otherconfig');
$productsconfig = Mage::getStoreConfig('mtcolinusadmin/productslist');
$style = 'style="width: '.$this->getConfig('items_width').'px;"';
$_catalog = $this->getListCategory();
$_helper = $this->helper('catalog/output');
$_productCollection=$this->getCollection();
if($_productCollection){
?>
<div id="mtcontainer" class="clickable clearfix container-custom ajax-product-container">
<?php $_collectionSize = $_productCollection->count() ?>
<?php
    $_columnCount = 4;
    $span = 12/$_columnCount;
    $i=0; foreach ($_productCollection as $_product):
?>
<?php
	$oType = false;
	$product = Mage::getModel('catalog/product');
	$product->load($_product->getId());
	foreach ($product->getOptions() as $o) {
		$optionType = $o->getType();
		if ($optionType == 'file') {
			$oType = true;
		}
	}
?>
    <?php $n = $i%$_columnCount;?>
    <?php if ($i++%$_columnCount==0): ?>
    <div class="mainproduct show-grid">
    <?php endif ?>
    <div class="item pull-left <?php if($n == 0):?>first<?php elseif($n == 3): ?>last<?php endif;?>" <?php echo $style;?>>
        <div class="content products-grid products-grid-ajax">
            <div class="product-image">
                <div class="product-thumb">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image">
                        <?php echo $this->helper('mtcolinusadmin')->getLabel($_product);  ?>
                        <?php if($productsconfig['hover_product']=='show_image'){?>
                            <img class="mt-hover" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w, $h); ?>" width="<?php echo $w?>" height="<?php echo $h?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <?php }?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($w,$h); ?>" width="<?php echo $w?>" height="<?php echo $h?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                    </a>
                </div>

                <div class="mask<?php if($productsconfig['hover_product']=='show_image'):?> show_text<?php endif; ?>" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                    <?php if( $this->getConfig('shortdescription') ){?>
                        <?php if ($_product->getShortDescription()):?>
                            <div class="short-description">
                                <?php
                                if($this->getConfig('desc_striptags')){
                                    $short_desc = strip_tags($_product->getShortDescription(), '<p>');
                                }else{
                                    $short_desc = $_product->getShortDescription();
                                }?>
                                <?php echo $_helper->productAttribute($_product, $short_desc, 'short_description') ?>
                            </div>
                        <?php endif;?>
                    <?php }?>
                    <?php if ( $this->getConfig('review') ){?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php }?>
                </div>
            </div>
            <div class="top-actions-inner">
                <span class="ajax-loading" id="ajax-loading<?php echo $_product->getId()?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'/skin/frontend/default/mt_colinus/images/loading.gif';?>"/></span>
                <?php if($this->getConfig('price')): ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
                <?php endif; ?>
                <div class="mt-actions clearfix">
                    <div class="addtocart pull-left br">
                        <?php if($otherconfig['enabled_ajax'] && $oType == false){?>
                            <?php if ( $this->getConfig('addtocart') ){?>
                                <?php if($_product->isSaleable()): ?>
                                    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="ajaxaddcart('<?php echo $this->getAddToCartUrl($_product) ?>',<?php echo $_product->getId() ?>)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php } else { ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <a href='<?php echo $this->getUrl('mtcolinusadmin/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Add</a>
                                    <?php }?>
                                <?php else: ?>
                                    <p class="availability out-of-stock pull-left">
                                        <span class="label" style="display:none;"><?php echo $this->__('Availability: ') ?></span>
                                        <span class="out" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span>
                                    </p>
                                <?php endif; ?>
                            <?php }?>
                        <?php }else{?>
                            <?php if ( $this->getConfig('addtocart') ){?>
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart-options" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock pull-left">
                                        <span class="label" style="display:none;"><?php echo $this->__('Availability: ') ?></span>
                                        <span class="out"><?php echo $this->__('Out of stock') ?></span>
                                    </p>
                                <?php endif; ?>
                            <?php } ?>
                        <?php }?>
                    </div>
                    <?php if ( $this->getConfig('addtowishlist') ){?>
                        <div class="wishlist pull-left br">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <p>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                                </p>
                            <?php endif; ?>
                        </div>
                    <?php }?>
                    <?php if ( $this->getConfig('addtocompare') ){?>
                        <div class="compare pull-left br">
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <p>
                                    <a href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                                </p>
                            <?php endif; ?>
                        </div>
                    <?php }?>
                    <?php if ( $this->getConfig('detail') ){?>
                        <div class="detail pull-left">
                            <button type="button" title="<?php echo $this->__('Detail') ?>" class="button btn-detail" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Detail') ?></span></span></button>
                        </div>
                    <?php }?>
                </div>
            </div>

        </div>
    </div>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </div>
    <?php endif ?>
<?php endforeach;?>
</div>
<?php if($otherconfig['hover_product']=='show_image'){?>
    <script type="text/javascript">
        var productHover = {
            over: function () {
                $mtkb('.mt-hover', this).animate({opacity: 1}, 200);
            },
            timeout: 20,
            out: function () {
                $mtkb('.mt-hover', this).animate({opacity: 0}, 200);
            }
        };
        $mtkb('.products-grid-ajax .product-image').hoverIntent(productHover);
    </script>
    <?php }?> 
<?php }?>