<div class="hidden-phone span4"> 

<div class="support header-static">	
<p class="span2">
	<span>Support</span>
</p>
<ul class="span10">
	<li><?php echo $this->__('support:') ?> <small><?php echo $this->__('+49 89 8996160') ?></small></li>
	<li><span><?php echo $this->__('Monday to Friday') ?>: 09:00am - 06:00pm </span></li>
</ul>	
</div>

</div>

<div class="hidden-phone span4"> 

<div class="email header-static">
<p class="span2">
	<span>Email</span>
</p>
<ul class="span10">
	<li><?php echo $this->__('Email:') ?> <a href="mailto:info@toptenstorage.com" title="info@toptenstorage.com">info@toptenstorage.com</a></li>
</ul>	
</div>
</div>