<?php
$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$config = Mage::getStoreConfig('mtcolinusadmin/social_config');
?>
<div class="span6"> 
	<div class="facebook">
	<div class="footer-static-title">
		<h3><?php echo $config['static_title_fb'];?></h3>
	</div>
	<div class="title-divider">
		<span>&nbsp;</span>
	</div>
	<?php if(!$config['facebook_replace']){?>
    <iframe scrolling="no" frameborder="0" class="FB_SERVER_IFRAME" src="http://www.facebook.com/connect/connect.php?href=<?php echo $config['facebook_page']?>&amp;width=250&amp;locale=&amp;connections=12&amp;stream=0&amp;logobar=0&amp;css=<?php echo $this->getSkinUrl().'css/fb.css'; ?>" allowtransparency="true" name="fbfanIFrame_0" style="width: 100%; height: 340px; border: medium none;"></iframe>
	<?php
}else{ 
	echo $this->getLayout()->createBlock('cms/block')->setBlockId($config['facebook_replace'])->toHtml();
}
?>
</div>
</div>
<div class="span6">
	<div class="twitter">
	<div class="footer-static-title">
		<h3><?php echo $config['static_title_twitter'];?></h3>
	</div>
	<div class="title-divider">
		<span>&nbsp;</span>
	</div>
	<?php if(!$config['twitter_replace']){?>
	<div id="mt-twitter">		
		<div class="mt-twitter-icon">
			<span><?php echo $this->__('1 minute ago');?></span>		   
			<a href="#" title="<?php echo $this->__('Retweet');?>"><?php echo $this->__('Retweet');?></a>
			<a href="#" title="<?php echo $this->__('Follow');?>"><?php echo $this->__('Follow');?></a>
		</div>		 
	</div>
	<?php 
}else{ 
	echo $this->getLayout()->createBlock('cms/block')->setBlockId($config['twitter_replace'])->toHtml();
}
?>
<?php if(!$config['twitter_replace'] || !$config['facebook_replace']){?>
<script>
<?php if(!$config['twitter_replace']){?>
	$mtkb('#mt-twitter').twitterTimeline({ 
		ajax: {
			data: {
				screen_name: '<?php echo $config['twitter_account']?>',
			}
		},
		count: <?php echo $config['twitter_numb']?>,
		refresh: 300000,
		tweetTemplate: function(item) {
			var dateRegEx = /^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) ([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2}) \+([0-9]{4}) ([0-9]{4})$/;
			var date = dateRegEx.exec(item.created_at); 
			var timeAgo = $mtkb.twitterTimeline.timeAgo(item.created_at);
			var tweet = '<div id="mt-twitter">'+
							'<p>' + $mtkb.twitterTimeline.parseTweet(item.text) + '</p>'+
							'<div class="icontwitter clearfix">'+
								'<span class="mt-icon pull-left"></span><span class="date pull-left">'+timeAgo+'</span>'+ 
							'</div>'+
						'</div>';
			return tweet;
		},
		animateAdd: function(el, idx) {
			return el.hide().delay(500*idx).slideDown(500);
		},
		animateRemove: function(el, idx) {
			el.delay(300*idx).slideUp(300, function() {
				el.remove();
			});
		}
	});
	<?php }?>
	<?php if(!$config['facebook_replace']){?>
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=218624181552972";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		<?php }?>
		</script> 
		<?php }?>
	</div>
</div>