<?php
$config = Mage::getStoreConfig('mtcolinusadmin/static_config');
$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
?>
<?php if ($config['static_product_view_sidebar']!=="" && $config['enabled_product_view_static']>0) : ?>
<div class="span<?php echo $config['static_product_view_sidebar_cols'];?> hidden-phone viewquicklook">
	<div class="products-view-sidebar">
		<?php echo str_replace('{baseurl}', $url, $config['static_product_view_sidebar']); ?>
	</div>
</div>
<?php endif; ?>

