<?php
/******************************************************
 * @package MT Slideshow module for Magento 1.4.x.x, Magento 1.5.x.x and Magento 1.6.x.x
 * @version 2.0.0
 * @author http://www.magentheme.com
 * @copyright (C) 2011- MagenTheme.Com
 * @license PHP files are GNU/GPL
*******************************************************/
?>
<?php
    foreach($this->getDataSlide() as $slide) {
        $template = Mage::getModel('mtslideshow/config_mode')->getTemplate($slide->getStyle());
        echo $this->getLayout()->createBlock('mtslideshow/mtslideshow')
                ->setSlideShow($slide)
                ->setTemplate($template)
                ->toHtml();
    }
?>