<?php 

$divid = 'jm-contain-'.rand().rand().time();
$classid = 'jm-products-slider-content'.rand().rand().time();
$_collectionSize = 0;
if($listall) $_collectionSize = $listall->count() ;

?>
 <?php if($configs['show']==1){ ?>

   	 <link rel="stylesheet"  href="<?php echo $this->getSkinUrl('mageclub/horizontalproductsslider/css/touchcarousel.css') ?>" />
   
	<!-- Skin stylesheets, include to your site only that what you need -->
	
	<link rel="stylesheet"  href="<?php echo $this->getSkinUrl('mageclub/horizontalproductsslider/css/grey-blue-skin.css') ?>" />

	<script type="text/javascript" src="<?php echo $this->getSkinUrl('mageclub/horizontalproductsslider/js/jquery.touchcarousel-1.1.min.js') ?>"></script>


<style>
		
		/**
		* Carousel with image and text, custom skinned scrollbar
		**/
		#carousel-image-and-text {
			width: <?php echo $configs['width_slideshow']; ?>px;
			height: auto;
			margin: 0 auto;	
		}	
		#carousel-image-and-text .arrow-holder {
			height: <?php echo $configs['itemheight']; ?>px;
		}		
		#carousel-image-and-text .touchcarousel-item {
			margin-right: 1px;	
			width: <?php echo $configs['itemwidth']; ?>px;
			height: <?php echo $configs['itemheight']; ?>px;		
		}
		#carousel-image-and-text .item-block {
			width: <?php echo $configs['width']; ?>px;
			height: <?php echo $configs['height']; ?>px;
			display: block;
		}
		#carousel-image-and-text .item-block img,
		#carousel-image-and-text .item-block h4, 
		#carousel-image-and-text .item-block p {
			float: left;
			position: relative;
			display: block;
			margin: 0;			
		}
		#carousel-image-and-text .item-block img {
			width: <?php echo $configs['width']; ?>px;
			height: <?php echo $configs['height']; ?>px;		
			border: 0;
			padding: 0;		
		}
		#carousel-image-and-text .item-block {			
			text-decoration: none;
			color: inherit;			
		}					
		
		#carousel-image-and-text .scrollbar-holder {
			background: #CED7DB;
			bottom: 0;
			height: 1px;
			left: 0;
			right: 0;
		}
		#carousel-image-and-text .scrollbar {
			background-color: #FBFBFB !important;
			bottom: 0;
		}
		
		
		
		
		
	</style>
<div id="carousel-image-and-text" class="touchcarousel grey-blue">  

	<?php if($_collectionSize){?>
	
			  	    		    	
		    	
		      	<ul class="touchcarousel-container">
		      					
						<?php foreach ($listall->getItems() as $_product){ ?>
		        			<li class="touchcarousel-item">
							<div style="text-align:center;width:<?php echo $configs['itemwidth']; ?>px;">
		        				<a  href="<?php echo $_product->getProductUrl() ?>">
		        					<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->keepAspectRatio(TRUE)->resize($configs['width'], $configs['height'])->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/> 
		        				</a>
								</div>
								<div style="text-align:center;width:<?php echo $configs['itemwidth']; ?>px;">
		        				<a class="product-title" title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
		        					<?php echo $_product->getName() ?>
		        				</a>
								</div>
	        					<?php if ($configs['show_price']) : ?>
								
	        					<div style="text-align:center;width:<?php echo $configs['itemwidth']; ?>px;">
	        					<?php echo $this->getPriceHtml($_product,true, '_jmslider') ?>
								</div>
	        					<?php endif; ?>
	        					<?php if($configs['show_cart']){ ?>
		        				<?php if($_product->isSaleable()){ ?>
									<div style="text-align:center;width:<?php echo $configs['itemwidth']; ?>px;">
										<button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span><?php echo $this->helper("catalog")->__('Add to Cart') ?></span>
										</button>
										<?php } else { ?>
											<div class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock') ?></div>
											<?php } ?>
											</div>
										<?php } ?>
										
		        			</li> 
							
					<?php } ?> 
		      </ul>
		   
	<?php } ?>
</div>
<script type="text/javascript"[]>
	jQuery.noConflict();
		jQuery(function(jQuery) {
		
			
			jQuery("#carousel-image-and-text").touchCarousel({	
                <?php if($configs['pagination']==1){ ?>			
				pagingNav: true,
				<?php } else { ?>
				pagingNav: false,
				<?php } ?>
				snapToItems: true,
				itemsPerMove: <?php echo $configs['no_items']; ?>,
                <?php if($configs['scroll_last']==1){ ?>					
				scrollToLast: true,
				<?php } else { ?>
                scrollToLast: false,
                <?php } if($configs['loop_items']==1){ ?>				
				loopItems: true,
				<?php } else { ?>
				loopItems: false,
				<?php } if($configs['autoplay']==1){ ?>
				autoplay: true,
				<?php } else { ?>
				autoplay: false,
				<?php } ?>
				autoplayDelay: <?php echo $configs['delay']; ?>,
				transitionSpeed: <?php echo $configs['speed']; ?>,
				<?php  if($configs['scroll_bar']==1){ ?>
				scrollbar: true
				<?php } else { ?>
				scrollbar: false
				<?php } ?>
		    });
			
			
		});
    </script>
<?php } ?>

